//authTypes
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

//cartTypes
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const ADD_AMOUNT = 'ADD_AMOUNT';
export const REDUCE_AMOUNT = 'REDUCE_AMOUNT';
export const AMOUNT_OF_PRODUCT = 'AMOUNT_OF_PRODUCT';
export const TOTAL_AMOUNT = 'TOTAL_AMOUNT';
export const BEGIN_ORDER = 'BEGIN_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_CART = 'CLEAR_CART';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

//productsTypes
export const GET_CURRENT_PRODUCT = 'GET_CURRENT_PRODUCT';
export const NO_CURRENT_PRODUCT = 'NO_CURRENT_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const PRODUCT_IS_DELETED = 'PRODUCT_IS_DELETED';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CATEGORY_IS_DELETED = 'CATEGORY_IS_DELETED';
export const CATEGORY_PRODUCT_ERROR = 'CATEGORY_PRODUCT_ERROR';
export const GET_CURRENT_CATEGORY = 'GET_CURRENT_CATEGORY';
export const NO_CURRENT_CATEGORY = 'NO_CURRENT_CATEGORY';

//reviewsTypes
export const CHANGE_RATE = 'CHANGE_RATE';
export const CHANGE_RATE_ERROR = 'CHANGE_RATE_ERROR';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';
export const CREATE_REVIEW_FOR_REVIEW = 'CREATE_REVIEW_FOR_REVIEW';
export const REVIEW_IS_DELETED = 'REVIEW_IS_DELETED';
export const DELETE_REVIEW_ERROR = 'DELETE_REVIEW_ERROR';

